server:
  port: 10010
spring:
  application:
    name: member-service-provider-10000 # 配置应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hsp
# 配置Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 执行mapper.xml文件位置
  type-aliases-package: com.charlie.springcloud.entity  # 实例类所在包，通过类名就可以引用
