server:
  port: 80
spring:
  application:
    name: e-commerce-consumer-openfeign-80
eureka:
  client:
    register-with-eureka: true  # 将自己注册到Eureka-Server
    fetch-registry: true        # 表示从eureka-server抓取注册信息
    service-url:
      # 表示将自己注册到哪个eureka-server，这里使用EurekaServer集群，使用逗号分隔
      defaultZone: http://eureka9001.com:9001/eureka,http://eureka9002.com:9002/eureka
#logging:
#  level:
#    # 对MemberFeignService接口调用过程打印信息-Debug
#    com.charlie.springcloud.service.MemberFeignService: debug
#ribbon: # OpenFeign超时设置
#  # 1. 设置feign客户端超时时间(openfeign默认支持ribbon)
#  # 2. ReadTimeout:8000 建立连接从服务提供方获取可用资源所用的全部时间，单位毫秒
#  ReadTimeout: 8000
#  # 两端连接所用时间
#  ConnectionTimeout: 8000