server:
  port: 10004
spring:
  application:
    name: member-service-nacos-provider # 配置应用名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/e_commerce_center_db?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hsp
  # 配置nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 配置nacos server地址
# 配置Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 执行mapper.xml文件位置
  type-aliases-package: com.charlie.springcloud.entity  # 实例类所在包，通过类名就可以引用
# 配置暴露所有的监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'